# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'STVProject2-3-2' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for STVProject2-3-2

  pod 'FMDB'

  target 'STVProject2-3-2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'STVProject2-3-2UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
