# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'STVProject2-2-1' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for STVProject2-2-1

  target 'STVProject2-2-1Tests' do

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ‘7.0’

pod 'AFNetworking', '~> 2.0’

    inherit! :search_paths
    # Pods for testing
  end

  target 'STVProject2-2-1UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
