# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'STVProject2-4-1' do

pod 'AFNetworking', '~> 3.0'

  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for STVProject2-4-1

  target 'STVProject2-4-1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'STVProject2-4-1UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
