# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'STVProject2-4-2' do

pod 'AFNetworking', '~> 3.0'
pod 'Realm'


  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for STVProject2-4-2

  target 'STVProject2-4-2Tests' do

pod 'Realm/Headers'

    inherit! :search_paths
    # Pods for testing
  end

  target 'STVProject2-4-2UITests' do

pod 'Realm/Headers'


    inherit! :search_paths
    # Pods for testing
  end

end
