# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'firebasePush_Kawahara' do

pod 'Firebase/Core'
pod 'Firebase/Messaging'

  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for firebasePush_Kawahara

  target 'firebasePush_KawaharaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'firebasePush_KawaharaUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
